In [8]:
import numpy as np
from numpy.random import randint

In [7]:
# implement quick sort recursively
def partition(par_by, data): # helper func to partition data
    
    first = [num for num in data if num<par_by]
    second = [num for num in data if num==par_by]
    third = [num for num in data if num>par_by]
    
    partitioned_data = first+second+third
    
    return partitioned_data

def quicksort(ls):
    if len(ls) <=1:
        return ls
    else:
        pivot =ls[0]
        new_ls = partition(pivot, ls)
        pivot_idx = new_ls.index(pivot)
        left_side = new_ls[:pivot_idx]
        right_side = new_ls[pivot_idx+1:]
        
        return quicksort(left_side) + [pivot] + quicksort(right_side)

In [27]:
short_input = randint(0, 1e4, 10)
long_input = randint(0,1e4, 10000)

In [12]:
%time sorted(short_input)

CPU times: user 20 µs, sys: 1 µs, total: 21 µs
Wall time: 26.7 µs


[1018, 2181, 3474, 3496, 6204, 6927, 8236, 8298, 8324, 8708]

In [13]:
%time quicksort(short_input)

CPU times: user 85 µs, sys: 1 µs, total: 86 µs
Wall time: 93 µs


[1018, 2181, 3474, 3496, 6204, 6927, 8236, 8298, 8324, 8708]

In [23]:
def bubblesort(ls): # each iteration of bubble sort moves max val to last index, lower stopping range after each iteration
    decreasing_index = (x for x in range(len(ls)-1, 0, -1)) 
    for i in decreasing_index:
        for j in range(i):
            if ls[j] > ls[j+1]:
                ls[j], ls[j+1] = ls[j+1], ls[j]
    return ls

In [28]:
short_input

array([5623, 9309, 7872, 8531, 2884,  920, 4081, 5669, 9479, 3059])

In [29]:
%time bubblesort(short_input)

CPU times: user 147 µs, sys: 27 µs, total: 174 µs
Wall time: 205 µs


array([ 920, 2884, 3059, 4081, 5623, 5669, 7872, 8531, 9309, 9479])

In [30]:
%time bubblesort(long_input)

CPU times: user 30.6 s, sys: 199 ms, total: 30.8 s
Wall time: 31.1 s


array([   0,    1,    2, ..., 9999, 9999, 9999])